//! Assembling a box and handing it to systemd-nspawn: the overlay mount, the
//! generated settings file, and the launch itself.

use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::Path;

use anyhow::{Context, Result};

use crate::argv;
use crate::config::{Network, UID_RANGE};
use crate::host::{dry_run, sh};
use crate::sandbox::{Bind, Sandbox, NSPAWN_DIR, STATE};
use crate::{base, info};

// --------------------------------------------------------------------------
// the overlay
// --------------------------------------------------------------------------

pub fn is_mounted(path: &Path) -> bool {
    let Ok(mountinfo) = fs::read_to_string("/proc/self/mountinfo") else {
        return false;
    };
    let target = path.to_string_lossy();
    mountinfo.lines().any(|line| {
        // fields: id parent dev:node root mountpoint ...
        line.split_whitespace().nth(4).is_some_and(|mp| mp == target)
    })
}

/// lower = the shared base image, upper = this box's writes. The overlay
/// features that rewrite how upper refers to lower are switched off: they buy
/// little here and interact badly with an image whose UIDs were shifted.
pub fn mount(sb: &Sandbox) -> Result<()> {
    if is_mounted(&sb.root()) {
        return Ok(());
    }
    base::require()?;
    for dir in [sb.upper(), sb.work(), sb.root()] {
        sh(argv!["mkdir", "-p", dir]).quiet().run()?;
    }
    let options = format!(
        "lowerdir={base},upperdir={upper},workdir={work},\
         index=off,metacopy=off,redirect_dir=off,xino=off",
        base = base::image().display(),
        upper = sb.upper().display(),
        work = sb.work().display(),
    );
    sh(argv![
        "mount",
        "-t",
        "overlay",
        format!("agentbox-{}", sb.name),
        "-o",
        options,
        sb.root()
    ])
    .run()?;
    Ok(())
}

pub fn umount(sb: &Sandbox) -> Result<()> {
    if is_mounted(&sb.root()) {
        sh(argv!["umount", sb.root()]).run()?;
    }
    Ok(())
}

// --------------------------------------------------------------------------
// the settings file
// --------------------------------------------------------------------------

/// Colons separate the fields of a `Bind=`, so they have to be escaped.
fn escape(path: &Path) -> String {
    path.to_string_lossy().replace('\\', r"\\").replace(':', r"\:")
}

/// One source of truth for both `agentbox shell` (which runs nspawn directly)
/// and `agentbox up` (which goes through systemd-nspawn@.service).
pub fn settings_text(sb: &Sandbox) -> String {
    let mut out = String::from("# generated by agentbox - edit .agentbox.toml instead\n");
    out.push_str("[Exec]\n");
    out.push_str(&format!("PrivateUsers={}:{}\n", sb.cfg.uid_base, UID_RANGE));
    out.push_str(&format!("User={}\n", sb.user.name));
    out.push_str(&format!("WorkingDirectory={}\n", sb.project.display()));
    out.push_str(&format!("Hostname={}\n", sb.hostname()));
    out.push_str("Timezone=copy\n");
    out.push_str("LinkJournal=no\n");
    out.push_str(match sb.cfg.network {
        Network::None => "ResolvConf=off\n",
        _ => "ResolvConf=copy-host\n",
    });
    for (key, value) in sb.env() {
        out.push_str(&format!("Environment={key}={value}\n"));
    }

    out.push_str("\n[Files]\n");
    // The image is pre-shifted on disk, so nothing needs chowning or mapping
    // at start; see docs/design.md.
    out.push_str("PrivateUsersOwnership=off\n");
    for bind in sb.binds() {
        let key = if bind.read_only { "BindReadOnly" } else { "Bind" };
        out.push_str(&format!(
            "{key}={}:{}:owneridmap\n",
            escape(&bind.src),
            escape(&bind.dst)
        ));
    }

    out.push_str("\n[Network]\n");
    out.push_str(match sb.cfg.network {
        Network::Host => "Private=no\nVirtualEthernet=no\n",
        Network::None => "Private=yes\nVirtualEthernet=no\n",
        Network::Nat => "Private=yes\nVirtualEthernet=yes\n",
    });
    out
}

pub fn write_settings(sb: &Sandbox) -> Result<()> {
    let text = settings_text(sb);
    if dry_run() {
        println!("--- {} ---", sb.settings().display());
        print!("{text}");
        return Ok(());
    }
    fs::create_dir_all(NSPAWN_DIR)?;
    fs::write(sb.settings(), text)
        .with_context(|| format!("cannot write {}", sb.settings().display()))
}

// --------------------------------------------------------------------------
// creating a box
// --------------------------------------------------------------------------

/// Idempotent: safe to call on every launch. Returns true if the box was new.
pub fn create(sb: &Sandbox) -> Result<bool> {
    let fresh = !sb.dir().exists();
    mount(sb)?; // checks that the base image exists
    if !dry_run() {
        fs::create_dir_all(sb.dir())?;
        write_meta(sb)?;
        seed_identity(sb)?;
        for bind in sb.binds() {
            prepare_mount_point(sb, &bind)?;
        }
        mask_host_network_units(sb)?;
    }
    write_settings(sb)?;
    if fresh && !dry_run() {
        set_login_shell(sb)?;
        if !sb.cfg.packages.is_empty() {
            info(&format!("installing packages: {}", sb.cfg.packages.join(" ")));
            let mut cmd = argv!["/usr/bin/pacman", "-Sy", "--noconfirm", "--needed"];
            cmd.extend(sb.cfg.packages.iter().map(crate::host::oss));
            run_in(sb, cmd, Some("root"), Some("/"))?;
        }
    }
    Ok(fresh)
}

fn write_meta(sb: &Sandbox) -> Result<()> {
    let meta = serde_json::json!({
        "name": sb.name,
        "project": sb.project,
        "user": sb.user.name,
        "uid_base": sb.cfg.uid_base,
        "network": sb.cfg.network.to_string(),
    });
    fs::write(sb.meta(), format!("{meta:#}\n"))
        .with_context(|| format!("cannot write {}", sb.meta().display()))
}

/// A machine ID generated once, and a hostname that follows the config.
fn seed_identity(sb: &Sandbox) -> Result<()> {
    let machine_id = sb.inside(Path::new("/etc/machine-id"));
    let unset = fs::read_to_string(&machine_id).map(|s| s.trim().is_empty()).unwrap_or(true);
    if unset {
        let mut bytes = [0u8; 16];
        getrandom(&mut bytes)?;
        let mut hex = String::with_capacity(33);
        for byte in bytes {
            use std::fmt::Write;
            write!(hex, "{byte:02x}")?;
        }
        hex.push('\n');
        fs::write(&machine_id, hex)?;
    }
    let hostname = sb.inside(Path::new("/etc/hostname"));
    let want = format!("{}\n", sb.hostname());
    if fs::read_to_string(&hostname).unwrap_or_default() != want {
        fs::write(&hostname, want)?;
    }
    Ok(())
}

fn getrandom(buf: &mut [u8]) -> Result<()> {
    let mut file = fs::File::open("/dev/urandom").context("cannot open /dev/urandom")?;
    std::io::Read::read_exact(&mut file, buf).context("cannot read /dev/urandom")
}

/// `owneridmap` maps the host owner of the source onto *the owner of the
/// destination inside the container*, so the mount point has to exist first,
/// owned by the right container user.
fn prepare_mount_point(sb: &Sandbox, bind: &Bind) -> Result<()> {
    let target = sb.inside(&bind.dst);
    let meta = fs::metadata(&bind.src)
        .with_context(|| format!("cannot stat {}", bind.src.display()))?;
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    if meta.is_dir() {
        if !target.exists() {
            fs::create_dir(&target)?;
        }
    } else if !target.exists() {
        fs::File::create(&target)?;
    }
    // Host UIDs outside the container's own range have no meaning inside it;
    // map those mounts onto container root instead.
    let inside = |id: u32| if id < UID_RANGE { id } else { 0 };
    std::os::unix::fs::chown(
        &target,
        Some(sb.shift(inside(meta.uid()))),
        Some(sb.shift(inside(meta.gid()))),
    )
    .with_context(|| format!("cannot chown {}", target.display()))
}

/// In host-network mode the box shares the host's network namespace, so a
/// booted box must never run networkd or resolved: it would reconfigure the
/// host's own interfaces. Mask them per box rather than in the shared base,
/// because nat mode needs networkd to bring up host0.
pub fn mask_host_network_units(sb: &Sandbox) -> Result<()> {
    let dir = sb.inside(Path::new("/etc/systemd/system"));
    fs::create_dir_all(&dir)?;
    for unit in [
        "systemd-networkd.service",
        "systemd-networkd.socket",
        "systemd-resolved.service",
    ] {
        let link = dir.join(unit);
        let masked = fs::read_link(&link).map(|t| t == Path::new("/dev/null")).unwrap_or(false);
        match sb.cfg.network {
            Network::Host if !masked => {
                let _ = fs::remove_file(&link);
                std::os::unix::fs::symlink("/dev/null", &link)?;
            }
            Network::Host => {}
            _ if masked => fs::remove_file(&link)?,
            _ => {}
        }
    }
    Ok(())
}

fn set_login_shell(sb: &Sandbox) -> Result<()> {
    let shell = sb.shell();
    run_in(
        sb,
        argv!["/usr/bin/chsh", "-s", shell, sb.user.name.clone()],
        Some("root"),
        Some("/"),
    )
    .map(|_| ())
}

// --------------------------------------------------------------------------
// launching
// --------------------------------------------------------------------------

fn launch_argv(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Vec<std::ffi::OsString> {
    // Settings files under /etc/systemd/nspawn are trusted, so `--settings=yes`
    // applies all of them while still letting these flags win.
    let mut args = argv![
        "systemd-nspawn",
        "-q",
        "-M",
        sb.name.clone(),
        "-D",
        sb.root(),
        "--settings=yes",
        "--as-pid2",
        "--register=no"
    ];
    if let Some(user) = user {
        args.extend(argv!["-u", user]);
    }
    if let Some(chdir) = chdir {
        args.push(crate::host::oss(format!("--chdir={chdir}")));
    }
    for (property, value) in [
        ("MemoryMax", &sb.cfg.memory_max),
        ("CPUQuota", &sb.cfg.cpu_quota),
        ("TasksMax", &sb.cfg.tasks_max),
    ] {
        if let Some(value) = value {
            args.push(crate::host::oss(format!("--property={property}={value}")));
        }
    }
    args.push(crate::host::oss("--"));
    args.extend(cmd);
    args
}

/// Run a command in the box and wait for it.
pub fn run_in(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Result<bool> {
    sh(launch_argv(sb, cmd, user, chdir)).quiet().run()
}

/// Replace this process with the box's payload, so it owns the terminal.
pub fn exec_in(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Result<std::convert::Infallible> {
    sh(launch_argv(sb, cmd, user, chdir)).quiet().exec()
}

pub fn state_dir() -> &'static Path {
    Path::new(STATE)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bind_paths_escape_the_field_separator() {
        assert_eq!(escape(Path::new("/plain/path")), "/plain/path");
        assert_eq!(escape(Path::new("/od:d")), r"/od\:d");
        assert_eq!(escape(Path::new(r"/back\slash")), r"/back\\slash");
    }
}
