//! Assembling a box and handing it to systemd-nspawn: the overlay mount, the
//! generated settings file, and the launch itself.

use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::argv;
use crate::config::{Network, UID_RANGE};
use crate::host::{dry_run, sh};
use crate::sandbox::{Bind, Sandbox, NSPAWN_DIR, UNIT_DIR};
use crate::{base, info};

// --------------------------------------------------------------------------
// the overlay
// --------------------------------------------------------------------------

pub fn is_mounted(path: &Path) -> bool {
    let Ok(mountinfo) = fs::read_to_string("/proc/self/mountinfo") else {
        return false;
    };
    let target = path.to_string_lossy();
    mountinfo.lines().any(|line| {
        // fields: id parent dev:node root mountpoint ...
        line.split_whitespace()
            .nth(4)
            .is_some_and(|mp| mp == target)
    })
}

/// lower = the shared base image, upper = this box's writes. The overlay
/// features that rewrite how upper refers to lower are switched off: they buy
/// little here and interact badly with an image whose UIDs were shifted.
pub fn mount(sb: &Sandbox) -> Result<()> {
    if is_mounted(&sb.root()) {
        return Ok(());
    }
    base::require()?;
    for dir in [sb.upper(), sb.work(), sb.root()] {
        sh(argv!["mkdir", "-p", dir]).quiet().run()?;
    }
    let options = format!(
        "lowerdir={base},upperdir={upper},workdir={work},\
         index=off,metacopy=off,redirect_dir=off,xino=off",
        base = base::image().display(),
        upper = sb.upper().display(),
        work = sb.work().display(),
    );
    sh(argv![
        "mount",
        "-t",
        "overlay",
        format!("agentbox-{}", sb.name),
        "-o",
        options,
        sb.root()
    ])
    .run()?;
    Ok(())
}

pub fn umount(sb: &Sandbox) -> Result<()> {
    if is_mounted(&sb.root()) {
        sh(argv!["umount", sb.root()]).run()?;
    }
    Ok(())
}

// --------------------------------------------------------------------------
// the settings file
// --------------------------------------------------------------------------

/// Colons separate the fields of a `Bind=`, so they have to be escaped.
fn escape(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', r"\\")
        .replace(':', r"\:")
}

/// One source of truth for both `agentbox shell` (which runs nspawn directly)
/// and `agentbox up` (which goes through systemd-nspawn@.service).
pub fn settings_text(sb: &Sandbox) -> String {
    let mut out = String::from("# generated by agentbox - edit .agentbox.toml instead\n");
    out.push_str("[Exec]\n");
    out.push_str(&format!("PrivateUsers={}:{}\n", sb.cfg.uid_base, UID_RANGE));
    // Deliberately no User= or WorkingDirectory=. This file applies to *every*
    // launch of the box, and `User=` names the user to invoke the container's
    // main process as - which for a booted box is systemd itself. Running PID 1
    // as the sandbox user leaves it unable to create /init.scope, so it dies
    // with "Failed to allocate manager object: Permission denied" a second
    // after `agentbox up` reports success. The direct launches pass both on the
    // command line instead, where they only affect that one payload.
    out.push_str(&format!("Hostname={}\n", sb.hostname()));
    out.push_str("Timezone=copy\n");
    out.push_str("LinkJournal=no\n");
    out.push_str(match sb.cfg.network {
        Network::None => "ResolvConf=off\n",
        _ => "ResolvConf=copy-host\n",
    });
    for (key, value) in sb.env() {
        out.push_str(&format!("Environment={key}={value}\n"));
    }

    out.push_str("\n[Files]\n");
    // The image is pre-shifted on disk, so nothing needs chowning or mapping
    // at start; see docs/design.md.
    out.push_str("PrivateUsersOwnership=off\n");
    for bind in sb.binds() {
        let key = if bind.read_only {
            "BindReadOnly"
        } else {
            "Bind"
        };
        out.push_str(&format!(
            "{key}={}:{}:owneridmap\n",
            escape(&bind.src),
            escape(&bind.dst)
        ));
    }

    out.push_str("\n[Network]\n");
    out.push_str(match sb.cfg.network {
        Network::Host => "Private=no\nVirtualEthernet=no\n",
        Network::None => "Private=yes\nVirtualEthernet=no\n",
        Network::Nat => "Private=yes\nVirtualEthernet=yes\n",
    });
    out
}

/// The configured resource caps, in the `systemctl set-property` spelling that
/// both `--property=` and a unit drop-in take.
fn caps(sb: &Sandbox) -> Vec<(&'static str, String)> {
    [
        ("MemoryMax", &sb.cfg.memory_max),
        ("CPUQuota", &sb.cfg.cpu_quota),
        ("TasksMax", &sb.cfg.tasks_max),
    ]
    .into_iter()
    .filter_map(|(key, value)| value.clone().map(|value| (key, value)))
    .collect()
}

/// Drop-in directory for this box's instance of `systemd-nspawn@.service`.
pub fn unit_dropin_dir(sb: &Sandbox) -> PathBuf {
    Path::new(UNIT_DIR).join(format!("{}.d", sb.service()))
}

/// Caps for a booted box.
///
/// A cap is a property of a unit, not of a container, so the generated .nspawn
/// file has nowhere to put it: `agentbox up` starts an instance of
/// systemd-nspawn@.service, and the caps belong in a drop-in on that. Rewritten
/// only when the content actually changes, since applying it costs a
/// daemon-reload.
pub fn write_unit_caps(sb: &Sandbox) -> Result<()> {
    let dir = unit_dropin_dir(sb);
    let path = dir.join("50-agentbox-caps.conf");
    let caps = caps(sb);
    let mut want = String::new();
    if !caps.is_empty() {
        want.push_str("# generated by agentbox - edit .agentbox.toml instead\n[Service]\n");
        for (key, value) in &caps {
            want.push_str(&format!("{key}={value}\n"));
        }
    }
    if dry_run() {
        if !want.is_empty() {
            println!("--- {} ---", path.display());
            print!("{want}");
        }
        return Ok(());
    }
    if fs::read_to_string(&path).unwrap_or_default() == want {
        return Ok(());
    }
    if want.is_empty() {
        let _ = fs::remove_file(&path);
        let _ = fs::remove_dir(&dir);
    } else {
        fs::create_dir_all(&dir)?;
        fs::write(&path, &want).with_context(|| format!("cannot write {}", path.display()))?;
    }
    daemon_reload()
}

/// Drop a box's caps drop-in, on the way to deleting the box.
pub fn clear_unit_caps(sb: &Sandbox) -> Result<()> {
    let dir = unit_dropin_dir(sb);
    if !dir.exists() {
        return Ok(());
    }
    fs::remove_dir_all(&dir).with_context(|| format!("cannot remove {}", dir.display()))?;
    daemon_reload()
}

fn daemon_reload() -> Result<()> {
    sh(argv!["systemctl", "daemon-reload"])
        .quiet()
        .run()
        .map(|_| ())
}

pub fn write_settings(sb: &Sandbox) -> Result<()> {
    let text = settings_text(sb);
    if dry_run() {
        println!("--- {} ---", sb.settings().display());
        print!("{text}");
        return Ok(());
    }
    fs::create_dir_all(NSPAWN_DIR)?;
    fs::write(sb.settings(), text)
        .with_context(|| format!("cannot write {}", sb.settings().display()))
}

// --------------------------------------------------------------------------
// creating a box
// --------------------------------------------------------------------------

/// Idempotent: safe to call on every launch. Returns true if the box was new.
pub fn create(sb: &Sandbox) -> Result<bool> {
    let fresh = !sb.dir().exists();
    mount(sb)?; // checks that the base image exists
    if !dry_run() {
        fs::create_dir_all(sb.dir())?;
        write_meta(sb)?;
        seed_identity(sb)?;
        for bind in sb.binds() {
            prepare_mount_point(sb, &bind)?;
        }
        mask_host_network_units(sb)?;
    }
    write_settings(sb)?;
    write_unit_caps(sb)?;
    if fresh && !dry_run() {
        set_login_shell(sb)?;
        if !sb.cfg.packages.is_empty() {
            info(&format!(
                "installing packages: {}",
                sb.cfg.packages.join(" ")
            ));
            let mut cmd = argv!["/usr/bin/pacman", "-Sy", "--noconfirm", "--needed"];
            cmd.extend(sb.cfg.packages.iter().map(crate::host::oss));
            run_in(sb, cmd, Some("root"), Some("/"))?;
        }
    }
    Ok(fresh)
}

fn write_meta(sb: &Sandbox) -> Result<()> {
    let meta = serde_json::json!({
        "name": sb.name,
        "project": sb.project,
        "user": sb.user.name,
        "uid_base": sb.cfg.uid_base,
        "network": sb.cfg.network.to_string(),
    });
    fs::write(sb.meta(), format!("{meta:#}\n"))
        .with_context(|| format!("cannot write {}", sb.meta().display()))
}

/// A machine ID generated once, and a hostname that follows the config.
fn seed_identity(sb: &Sandbox) -> Result<()> {
    let machine_id = sb.inside(Path::new("/etc/machine-id"));
    let unset = fs::read_to_string(&machine_id)
        .map(|s| s.trim().is_empty())
        .unwrap_or(true);
    if unset {
        let mut bytes = [0u8; 16];
        getrandom(&mut bytes)?;
        let mut hex = String::with_capacity(33);
        for byte in bytes {
            use std::fmt::Write;
            write!(hex, "{byte:02x}")?;
        }
        hex.push('\n');
        fs::write(&machine_id, hex)?;
    }
    let hostname = sb.inside(Path::new("/etc/hostname"));
    let want = format!("{}\n", sb.hostname());
    if fs::read_to_string(&hostname).unwrap_or_default() != want {
        fs::write(&hostname, want)?;
    }
    Ok(())
}

fn getrandom(buf: &mut [u8]) -> Result<()> {
    let mut file = fs::File::open("/dev/urandom").context("cannot open /dev/urandom")?;
    std::io::Read::read_exact(&mut file, buf).context("cannot read /dev/urandom")
}

/// Container paths systemd-nspawn covers with a mount of its own.
///
/// Custom binds are set up *after* those, so a mount point prepared below one
/// of them is invisible by the time it matters: nspawn creates its own target
/// inside its tmpfs, owned by container root, and `owneridmap` then maps the
/// host owner onto container root rather than onto the sandbox user. A mode
/// 700 project directory becomes unenterable, and the failure surfaces as
/// nspawn refusing to chdir into it.
///
/// Supporting these destinations means picking a cost: `idmap` instead of
/// `owneridmap` would map container root to host root on the mount, which
/// hands the box a way to leave setuid-root binaries in the project; binding
/// our own directory over nspawn's tmpfs would make the box's /tmp persist in
/// the overlay instead of being a tmpfs. Until one is chosen, say so plainly.
const NSPAWN_OWNED: [&str; 5] = ["/tmp", "/run", "/dev", "/proc", "/sys"];

fn shadowed_by_nspawn(dst: &Path) -> Option<&'static str> {
    NSPAWN_OWNED.into_iter().find(|base| dst.starts_with(base))
}

/// `owneridmap` maps the host owner of the source onto *the owner of the
/// destination inside the container*, so the mount point has to exist first,
/// owned by the right container user.
fn prepare_mount_point(sb: &Sandbox, bind: &Bind) -> Result<()> {
    if let Some(base) = shadowed_by_nspawn(&bind.dst) {
        bail!(
            "cannot map {} at {} inside the box: systemd-nspawn mounts its own \
             {base} there, which hides the mount point agentbox prepares, so \
             the sandbox user would not own it. Use a path outside {base}.",
            bind.src.display(),
            bind.dst.display(),
        );
    }
    let target = sb.inside(&bind.dst);
    let meta =
        fs::metadata(&bind.src).with_context(|| format!("cannot stat {}", bind.src.display()))?;
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    if meta.is_dir() {
        if !target.exists() {
            fs::create_dir(&target)?;
        }
    } else if !target.exists() {
        fs::File::create(&target)?;
    }
    // Host UIDs outside the container's own range have no meaning inside it;
    // map those mounts onto container root instead.
    let inside = |id: u32| if id < UID_RANGE { id } else { 0 };
    std::os::unix::fs::chown(
        &target,
        Some(sb.shift(inside(meta.uid()))),
        Some(sb.shift(inside(meta.gid()))),
    )
    .with_context(|| format!("cannot chown {}", target.display()))
}

/// In host-network mode the box shares the host's network namespace, so a
/// booted box must never run networkd or resolved: it would reconfigure the
/// host's own interfaces. Mask them per box rather than in the shared base,
/// because nat mode needs networkd to bring up host0.
pub fn mask_host_network_units(sb: &Sandbox) -> Result<()> {
    let dir = sb.inside(Path::new("/etc/systemd/system"));
    fs::create_dir_all(&dir)?;
    for unit in [
        "systemd-networkd.service",
        "systemd-networkd.socket",
        "systemd-resolved.service",
    ] {
        let link = dir.join(unit);
        let masked = fs::read_link(&link)
            .map(|t| t == Path::new("/dev/null"))
            .unwrap_or(false);
        match sb.cfg.network {
            Network::Host if !masked => {
                let _ = fs::remove_file(&link);
                std::os::unix::fs::symlink("/dev/null", &link)?;
            }
            Network::Host => {}
            _ if masked => fs::remove_file(&link)?,
            _ => {}
        }
    }
    Ok(())
}

fn set_login_shell(sb: &Sandbox) -> Result<()> {
    let shell = sb.shell();
    run_in(
        sb,
        argv!["/usr/bin/chsh", "-s", shell, sb.user.name.clone()],
        Some("root"),
        Some("/"),
    )
    .map(|_| ())
}

// --------------------------------------------------------------------------
// launching
// --------------------------------------------------------------------------

/// True only when stdin, stdout and stderr are all terminals.
///
/// nspawn decides how to wire up the payload from whether it was "invoked on a
/// terminal", and either answer is wrong for a redirected launch. Invoked with
/// a terminal it allocates a pseudo-TTY, so piped stdout arrives as CRLF with
/// stderr merged into it, and EOF cannot propagate through a shell pipeline;
/// invoked without one it defaults to `read-only`, which drops our stdin. Both
/// make `agentbox run` unusable as a pipeline component, so anything short of
/// fully interactive asks for the raw descriptors instead.
fn interactive_stdio() -> bool {
    // SAFETY: isatty only inspects the descriptor.
    (0..=2).all(|fd| unsafe { libc::isatty(fd) } == 1)
}

fn launch_argv(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Vec<std::ffi::OsString> {
    // Settings files under /etc/systemd/nspawn are trusted, so `--settings=yes`
    // applies all of them while still letting these flags win.
    // Resource caps have to sit on a unit, and nspawn allocates none of its own
    // here: with --register=no the container simply inherits the caller's
    // cgroup, so `--property=` had nowhere to land and every cap read back as
    // the session default. Launch inside a transient scope of our own instead.
    // Delegate=yes mirrors the stock systemd-nspawn@.service - nspawn creates
    // its payload and supervisor subgroups below the scope.
    let mut args: Vec<std::ffi::OsString> = Vec::new();
    let caps = caps(sb);
    if !caps.is_empty() {
        args.extend(argv![
            "systemd-run",
            "--scope",
            "--quiet",
            "--property=Delegate=yes"
        ]);
        for (key, value) in &caps {
            args.push(crate::host::oss(format!("--property={key}={value}")));
        }
        // Not optional: systemd-run has its own -q and -M, and getopt would
        // otherwise be free to read nspawn's flags as its own.
        args.push(crate::host::oss("--"));
    }
    args.extend(argv![
        "systemd-nspawn",
        "-q",
        "-M",
        sb.name.clone(),
        "-D",
        sb.root(),
        "--settings=yes",
        "--as-pid2",
        "--register=no"
    ]);
    // The man page's caution about handing file descriptors to the payload is
    // the reason this is conditional: pipe mode is chosen precisely when they
    // are not terminals. A terminal stdin can still be passed through when
    // only the output is redirected, which is what TIOCSTI would abuse - that
    // ioctl is off by default since Linux 6.2 (dev.tty.legacy_tiocsti).
    if !interactive_stdio() {
        args.push(crate::host::oss("--console=pipe"));
    }
    if let Some(user) = user {
        args.extend(argv!["-u", user]);
    }
    if let Some(chdir) = chdir {
        args.push(crate::host::oss(format!("--chdir={chdir}")));
    }
    args.push(crate::host::oss("--"));
    args.extend(cmd);
    args
}

/// Run a command in the box and wait for it.
pub fn run_in(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Result<bool> {
    sh(launch_argv(sb, cmd, user, chdir)).quiet().run()
}

/// Replace this process with the box's payload, so it owns the terminal.
pub fn exec_in(
    sb: &Sandbox,
    cmd: Vec<std::ffi::OsString>,
    user: Option<&str>,
    chdir: Option<&str>,
) -> Result<std::convert::Infallible> {
    sh(launch_argv(sb, cmd, user, chdir)).quiet().exec()
}

pub use crate::sandbox::state_dir;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bind_paths_escape_the_field_separator() {
        assert_eq!(escape(Path::new("/plain/path")), "/plain/path");
        assert_eq!(escape(Path::new("/od:d")), r"/od\:d");
        assert_eq!(escape(Path::new(r"/back\slash")), r"/back\\slash");
    }

    #[test]
    fn destinations_nspawn_would_shadow_are_recognised() {
        assert_eq!(shadowed_by_nspawn(Path::new("/tmp/project")), Some("/tmp"));
        assert_eq!(shadowed_by_nspawn(Path::new("/run/x")), Some("/run"));
        assert_eq!(shadowed_by_nspawn(Path::new("/tmp")), Some("/tmp"));
    }

    /// Component-wise, so a directory merely starting with those letters is
    /// not mistaken for one of them.
    #[test]
    fn ordinary_destinations_are_left_alone() {
        for dst in ["/home/me/code", "/srv/work", "/tmpfoo/x", "/var/tmp/x"] {
            assert_eq!(shadowed_by_nspawn(Path::new(dst)), None, "{dst}");
        }
    }
}
